# ETL 스케줄링

- 매일 업데이트 되는 csv파일을 임시로 담는 테이블
- 임시 테이블 -> 원본 테이블로 중복값 제거 후 적재
- ETL 스케줄링에 사용할 temp 테이블 7개 생성
  - movie_codes_temp
  - movie_company_temp
  - movie_director_temp
  - movie_genre_temp
  - movie_grade_temp
  - movie_sale_temp
  - movie_summary_temp

In [ ]:
CREATE TABLE raw_data.movie_codes_temp(
    movieNm VARCHAR(150),
    movieCd VARCHAR(10) primary key
)

In [ ]:
CREATE TABLE raw_data.movie_company_temp(
    movieCd VARCHAR(10) primary key,
    companys VARCHAR(100)
);

In [ ]:
CREATE TABLE raw_data.movie_director_temp(
    movieCd VARCHAR(10) primary key,
    directors VARCHAR(50)
);

In [ ]:
CREATE TABLE raw_data.movie_genre_temp(
    movieCd VARCHAR(10) primary key,
    genres VARCHAR(20)
);

In [ ]:
CREATE TABLE raw_data.movie_grade_temp(
    movieCd VARCHAR(10) primary key,
    audits VARCHAR(80)
);

In [ ]:
CREATE TABLE raw_data.movie_sale_temp(
    date DATE,
    rank INTEGER,
    rankInten INTEGER,
    rankOldAndNew VARCHAR(10),
    movieCd INTEGER primary key,
    movieNm VARCHAR(150),
    openDt DATE,
    salesAmt FLOAT,
    salesShare FLOAT,
    salesInten FLOAT,
    salesChange FLOAT,
    salesAcc FLOAT,
    audiCnt INTEGER,
    audiInten INTEGER,
    audiChange FLOAT,
    audiAcc INTEGER,
    scrnCnt INTEGER,
    showCnt INTEGER
);

In [ ]:
CREATE TABLE raw_data.movie_summary_temp(
    movieCd INTEGER primary key,
    movieNm VARCHAR(150),
    movieNmEn VARCHAR(150),
    showTm INTEGER,
    prdtYear VARCHAR(10),
    openDt DATE,
    actors VARCHAR(50) 
);